baseurl = "https://jesselang.com/"
languageCode = "en-US"
title = "Jesse Lang"
# Enable comments by entering your Disqus shortname
disqusShortname = "jesselang"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-31809303-1"
theme = "hugo-sustain"

[permalinks]
  blog = "/:year/:month/:slug"

[params]
  avatar = "profile.jpg"
  author = "Jesse Lang"
  description = ""

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "jesselang"
  Email         = ""
  Twitter       = "jesselang"
  LinkedIn      = "jesselang"
  Stackoverflow = ""

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"

