baseURL = "https://www.jesselang.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Jesse Lang"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Google Analytics
googleAnalytics = "UA-31809303-1"

[permalinks]
  blog = "/:year/:month/:slug"

[params]
title = "Hi. I'm Jesse Lang."
author = "Jesse Lang"
description = "Forgiven. Son, husband, father; open-source geek."
profilePicture = "img/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["blog"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/jesselang"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/jesselang/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/jesselang"

#[[params.socialIcons]]
#icon = "fa-envelope"
#title = "e-mail"
#url = "mailto:"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

#  [[menu.main]]
#  name = "About"
#  weight = 300
#  identifier = "about"
#  url = "/about/"
