baseURL = "https://www.jesselang.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Jesse Lang"

canonifyURLs = true
enableRobotsTXT = true

theme = "anatole"
summarylength = 10
enableEmoji = true

# Google Analytics
googleAnalytics = "UA-31809303-1"

[permalinks]
  post = "/:year/:month/:slug"
  page = "/:slug"

[params]
title = "Hi. I'm Jesse Lang."
author = "Jesse Lang"
description = "Forgiven. Son, husband, father; open-source geek."
profilePicture = "img/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]

# Overridden at build time
commitHash = ""

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/jesselang"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/jesselang/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/jesselang"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"
